import NavBar from "@/components/NavBar/nav-bar";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SideBarContextProvider>
        <body className="mx-auto h-screen relative flex flex-col bg-zinc-900 overflow-x-hidden 2xl:max-w-7xl">
          <NavBar />
          <section className="w-full flex flex-row">
            <SideBar />
            {children}
          </section>
        </body>
      </SideBarContextProvider>
    </html>
  );
}
